// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function emptyWord(id) {
  return {
          id: id
        };
}

var foo = "hi";

exports.emptyWord = emptyWord;
exports.foo = foo;
/* No side effect */
